apiVersion: v1
kind: ConfigMap
metadata:
  name: table-reservation
  namespace: staynest
  labels: { app.kubernetes.io/name: table-reservation, staynest.io/domain: fnb }
data:
  LOG_LEVEL: info
  PORT: "50162"
