apiVersion: v1
kind: Service
metadata:
  name: table-reservation
  namespace: staynest
  labels: { app.kubernetes.io/name: table-reservation, staynest.io/domain: fnb }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50162, targetPort: 50162 }]
  selector: { app.kubernetes.io/name: table-reservation }
