apiVersion: v1
kind: ConfigMap
metadata:
  name: banquet-service
  namespace: staynest
  labels: { app.kubernetes.io/name: banquet-service, staynest.io/domain: event }
data:
  LOG_LEVEL: info
  PORT: "50200"
