---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: api-gateway, namespace: staynest }
spec:
  minAvailable: 2
  selector:
    matchLabels: { app.kubernetes.io/name: api-gateway }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: inventory-service, namespace: staynest }
spec:
  minAvailable: 3
  selector:
    matchLabels: { app.kubernetes.io/name: inventory-service }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: pms-service, namespace: staynest }
spec:
  minAvailable: 2
  selector:
    matchLabels: { app.kubernetes.io/name: pms-service }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: crs-service, namespace: staynest }
spec:
  minAvailable: 2
  selector:
    matchLabels: { app.kubernetes.io/name: crs-service }
