apiVersion: v1
kind: ConfigMap
metadata:
  name: invoice-service
  namespace: staynest
  labels: { app.kubernetes.io/name: invoice-service, staynest.io/domain: finance }
data:
  LOG_LEVEL: info
  PORT: "50242"
