apiVersion: v1
kind: ConfigMap
metadata:
  name: room-service
  namespace: staynest
  labels: { app.kubernetes.io/name: room-service, staynest.io/domain: pms }
data:
  LOG_LEVEL: info
  PORT: "50040"
