apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata: { name: staynest-cosign }
spec:
  images:
    - glob: "harbor.staynest.internal/staynest/*"
  authorities:
    - name: keyless-github
      keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: https://token.actions.githubusercontent.com
            subjectRegExp: 'https://github.com/prabhat-roy/StayNest/.*'
