apiVersion: v1
kind: Service
metadata:
  name: yield-service
  namespace: staynest
  labels: { app.kubernetes.io/name: yield-service, staynest.io/domain: rms }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50083, targetPort: 50083 }]
  selector: { app.kubernetes.io/name: yield-service }
