apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staynest-aws
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/prabhat-roy/StayNest.git
        revision: HEAD
        directories:
          - path: helm/charts/*
  template:
    metadata:
      name: '{{path.basename}}-aws'
      labels:
        cloud: aws
        staynest.io/managed-by: argocd
    spec:
      project: staynest
      source:
        repoURL: https://github.com/prabhat-roy/StayNest.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles: [values.yaml, values-aws.yaml]
      destination:
        server: https://kubernetes.default.svc
        namespace: staynest
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
