apiVersion: v1
kind: ConfigMap
metadata:
  name: menu-service
  namespace: staynest
  labels: { app.kubernetes.io/name: menu-service, staynest.io/domain: fnb }
data:
  LOG_LEVEL: info
  PORT: "50161"
