apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: staynest
  labels: { app.kubernetes.io/name: menu-service, staynest.io/domain: fnb }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50161, targetPort: 50161 }]
  selector: { app.kubernetes.io/name: menu-service }
