apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata: { name: staynest-domain-deploy, namespace: argo }
spec:
  entrypoint: deploy
  arguments:
    parameters:
      - { name: domain }
      - { name: cloud }
      - { name: version }
  templates:
    - name: deploy
      steps:
        - - { name: status-page,  template: cachet-update }
        - - { name: db-migration, template: flyway-migrate }
        - - { name: helm-upgrade, template: helm }
        - - { name: smoke-tests,  template: hurl-smoke }
    - name: cachet-update
      container: { image: staynest/jenkins-agent:latest }
    - name: flyway-migrate
      container: { image: flyway/flyway:10 }
    - name: helm
      container: { image: alpine/helm:3.16 }
    - name: hurl-smoke
      container: { image: ghcr.io/orange-opensource/hurl:5.0.1 }
