image: { repository: ghcr.io/postalserver/postal, tag: 3.3.4 }
hostname: postal.staynest.internal
mariadb: { enabled: true }
rabbitmq: { enabled: true }
ingress:
  enabled: true
  hosts: [{ host: postal.staynest.internal }]
