apiVersion: v1
kind: ConfigMap
metadata: { name: hubble-config, namespace: kube-system }
data:
  hubble.yaml: |
    enable: true
    metrics:
      enabled: [dns, drop, tcp, flow, port-distribution, icmp, http]
