apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata: { name: staynest, namespace: observability }
spec:
  strategy: production
  storage:
    type: elasticsearch
    options: { es: { server-urls: "http://elasticsearch:9200", index-prefix: jaeger-staynest } }
  sampling:
    options:
      default_strategy: { type: probabilistic, param: 0.05 }
