apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-service
  namespace: staynest
  labels: { app.kubernetes.io/name: wallet-service, staynest.io/domain: loyalty }
data:
  LOG_LEVEL: info
  PORT: "50223"
