apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: staynest
  labels: { app.kubernetes.io/name: wallet-service, staynest.io/domain: loyalty }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50223, targetPort: 50223 }]
  selector: { app.kubernetes.io/name: wallet-service }
