.PHONY: build test run lint tidy docker-build

build:
	go build -o bin/av-service .

test:
	go test ./... -v -race

run:
	go run .

tidy:
	go mod tidy

lint:
	golangci-lint run ./...

docker-build: tidy
	docker build -t staynest/av-service:latest .

docker-run:
	docker run --rm -p 50201:50201 --env-file .env staynest/av-service:latest
