apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service
  namespace: staynest
  labels: { app.kubernetes.io/name: profile-service, staynest.io/domain: guest }
data:
  LOG_LEVEL: info
  PORT: "50120"
