apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata: { name: staynest, namespace: flux-system }
spec:
  interval: 1m
  url: https://github.com/prabhat-roy/StayNest.git
  ref: { branch: main }
