apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: staynest
  labels: { app.kubernetes.io/name: billing-service, staynest.io/domain: finance }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50240, targetPort: 50240 }]
  selector: { app.kubernetes.io/name: billing-service }
